"""Narrow structural ports exposed to tool execution contexts."""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any, Protocol


class ArtifactStorePort(Protocol):
    async def put(self, **values: Any) -> Any: ...
    async def read(
        self, artifact_id: str, **values: Any
    ) -> tuple[Any, bytes, bool]: ...


class CollaborationPort(Protocol):
    mailbox_enabled: bool

    async def delegate(self, contracts: Iterable[Any], **values: Any) -> list[Any]: ...
    async def status(self, task_id: str, **values: Any) -> Any: ...
    async def cancel(self, task_id: str) -> None: ...
    async def send_message(self, task_id: str, **values: Any) -> Any: ...
    async def read_messages(self, task_id: str, **values: Any) -> list[Any]: ...
    async def acknowledge_message(self, message_id: str, **values: Any) -> None: ...
    async def send_child_message(self, **values: Any) -> Any: ...
    async def read_child_messages(self, **values: Any) -> list[Any]: ...
    async def acknowledge_child_message(
        self, message_id: str, **values: Any
    ) -> None: ...
    async def publish_artifact(self, task_id: str, **values: Any) -> Any: ...


class ProcessManagerPort(Protocol):
    def get(self, session_id: str, identifier: str) -> Any: ...
    async def stop(self, session_id: str, identifier: str) -> Any: ...


class PermissionEnginePort(Protocol):
    async def has_explicit_restriction(self, **values: Any) -> bool: ...


class ToolCatalogPort(Protocol):
    def search(self, query: str, limit: int, **values: Any) -> tuple[str, ...]: ...
    def snapshot(self) -> Any: ...


class DiscoveryStorePort(Protocol):
    async def record_tool_discoveries(
        self, session_id: str, names: list[str], generation: int
    ) -> None: ...


class ShellClassifierPort(Protocol):
    async def classify(self, **values: Any) -> Any: ...


class PlanningRepositoryPort(Protocol):
    async def create_enter_request(
        self, session_id: str, objective: str, **values: Any
    ) -> Any: ...
    async def submit(self, plan_id: str, **values: Any) -> Any: ...


class PlanningPort(Protocol):
    repository: PlanningRepositoryPort

    async def is_active(self, session_id: str) -> bool: ...
    async def current(self, session_id: str) -> Any: ...
    async def attachment(self, session_id: str) -> Any: ...
    async def update(self, session_id: str, content: str, **values: Any) -> Any: ...


class RunGovernorPort(Protocol):
    def remaining_seconds(self) -> float | None: ...
    async def current(self) -> Any: ...
    async def before_tool(self, name: str, arguments: dict[str, Any]) -> Any: ...
    async def finish_tool(self, attempt_id: int, **values: Any) -> None: ...
    async def record_external_usage(self, **values: Any) -> None: ...
    async def stop(self, reason: Any) -> None: ...


__all__ = [
    "ArtifactStorePort",
    "CollaborationPort",
    "DiscoveryStorePort",
    "PermissionEnginePort",
    "PlanningPort",
    "ProcessManagerPort",
    "RunGovernorPort",
    "ShellClassifierPort",
    "ToolCatalogPort",
]
