"""Child Agent collaboration port."""

from __future__ import annotations

from typing import Any, AsyncIterator, Protocol


class CollaborationPort(Protocol):
    async def delegate(self, contracts: Any) -> list[Any]: ...
    def stream_status(self, task_ids: Any) -> AsyncIterator[dict[str, Any]]: ...
    async def wait(self, task_id: str) -> Any: ...
    async def validated_output(self, task_id: str) -> Any: ...
    async def cancel(self, task_id: str) -> None: ...
    async def cleanup(self, task_id: str) -> None: ...
