"""Model audit and run governance ports."""

from __future__ import annotations

from typing import Any, Protocol


class ModelAuditPort(Protocol):
    async def record_decision(self, run_id: str, **values: Any) -> int: ...
    async def start_call(self, run_id: str, **values: Any) -> str: ...
    async def finish_call(self, call_id: str, **values: Any) -> None: ...
    async def record_budget(self, run_id: str, **values: Any) -> None: ...
    async def usage(self, run_id: str) -> tuple[int, int, float]: ...
    async def session_cost(self, run_id: str) -> float: ...
    async def summary(self, run_id: str) -> list[dict[str, Any]]: ...


class GovernancePort(Protocol):
    async def start(self, run_id: str, **values: Any) -> tuple[Any, list[Any]]: ...
    async def save(self, run_id: str, **values: Any) -> None: ...
    async def reserve_attempt(self, run_id: str, **values: Any) -> int: ...
    async def finish_attempt(self, attempt_id: int, **values: Any) -> None: ...
