"""Single source of truth for evaluated behavioural defaults.

Safety ceilings deliberately remain next to their validators. Values in this
module are tunable defaults and may only be changed with an approved evaluation
recommendation.
"""

from __future__ import annotations

DEFAULT_PROVIDER_TIMEOUT_SECONDS = 60.0
DEFAULT_MAX_TOOL_ROUNDS = 32
DEFAULT_MAX_READ_CONCURRENCY = 4
DEFAULT_MAX_ARGUMENT_REPAIR_ATTEMPTS = 1

DEFAULT_CONTEXT_TRIGGER_RATIO = 0.80
DEFAULT_CONTEXT_TARGET_RATIO = 0.60
DEFAULT_CONTEXT_PRESERVE_RECENT_TURNS = 6
DEFAULT_CONTEXT_PRESERVE_RECENT_TOKENS = 32_768
DEFAULT_CONTEXT_MAX_COMPACTION_FAILURES = 3

DEFAULT_LOOP_CONSECUTIVE_REPEATS = 3
DEFAULT_LOOP_FAILED_RETRIES = 3
DEFAULT_LOOP_CYCLE_REPETITIONS = 3
DEFAULT_LOOP_MAX_CYCLE_LENGTH = 4

DEFAULT_AGENT_MAX_CHILDREN = 4
DEFAULT_AGENT_MAX_CONCURRENCY = 2
DEFAULT_AGENT_MAX_DEPTH = 1
DEFAULT_AGENT_MAX_CHILD_TOOL_ROUNDS = 16

DEFAULT_MEMORY_RECALL_LIMIT = 5
DEFAULT_MEMORY_RECALL_BYTES = 4_096
DEFAULT_MEMORY_RECALL_THRESHOLD = 0.50
DEFAULT_MEMORY_SEMANTIC_THRESHOLD = 0.45
DEFAULT_MEMORY_RETRIEVAL_WEIGHT = 0.72
DEFAULT_MEMORY_SCOPE_WEIGHT = 0.08
DEFAULT_MEMORY_CONFIDENCE_WEIGHT = 0.08
DEFAULT_MEMORY_FRESHNESS_WEIGHT = 0.06
DEFAULT_MEMORY_SOURCE_VALIDITY_WEIGHT = 0.06

__all__ = [name for name in globals() if name.startswith("DEFAULT_")]
